chanzuckerberg/cellxgene-census

api/python/cell_census/setup.cfg, cell_census_builder/globals.py
Fixes #16 
Unrelated: also included a bit of additional metadata on the cell_census package
=> specification update wrt multi-species genes

api/python/cell_census/release_process.md
More clarification and copyediting of the release process doc.
=> refinement of release process doc

api/python/notebooks/api_demo/census_high_variable_genes.ipynb
Note to self: Always Run All The Notebooks™️
=> fix notebook import

tools/cell_census_builder/__main__.py, tools/cell_census_builder/validate.py
Create the soma_path and asset_path the same way for `builder` and `validate` in `cell_census_builder`
=> Remove logic duplication in validator

api/python/notebooks/README.md
=> update installation docs to reflect publication of package on PyPi

.github/workflows/unittests.yml
Add a Github Action workflow (a step, really) for running the builder test.
=> GitHub Action workflow for builder unit test

tools/cell_census_builder/scripts/release/census_summary.py
Resolves #170 
- move cell counts first
- show all of Pandas DataFrame output, but remove dimensions
- show dataset delta counts
=> feature: builder census summary tweaks

tools/cell_census_builder/manifest.py
=> remove workaround for portal API gateway error bug

.pre-commit-config.yaml, tools/cell_census_builder/datasets.py, tools/cell_census_builder/util.py
Fixes #130 
changes:
* updated to mypy version 1.0
* added pandas-stubs for both cell_census and builder checks
=> update to mypy 1.0

.github/workflows/unittests.yml, README.md, api/python/cell_census/scripts/requirements-dev.txt, tools/scripts/requirements-dev.txt
- run coverage with unit-tests
- add coverage to requirements-dev.txt
- send coverage results to codecov
=> Add codecov github action

api/python/cell_census/src/cell_census/__init__.py, api/python/cell_census/src/cell_census/experiment.py, api/python/cell_census/src/cell_census/get_anndata.py, api/python/cell_census/src/cell_census/open.py, api/python/cell_census/src/cell_census/presence_matrix.py, api/python/cell_census/src/cell_census/util.py, api/python/cell_census/tests/test_get_helpers.py, api/python/cell_census/tests/test_util.py
Fixes #137 
Changes:
* removed get_experiment
* added module-level help string
* fixed a few docstring typos
* renamed private methods to include underscore prefix
=> API cleanup

api/python/notebooks/analysis_demo/comp_bio_census_info.ipynb, api/python/notebooks/analysis_demo/comp_bio_query_data_and_metadata.ipynb
Small fix to notebooks that had incorrect header levels ("#" instead of "##")
=> docs: fix header level of notebooks

tools/cell_census_builder/tests/test_main.py
Adding unit test for the builder arg parser. 
Part of #139
=> add tests for builder arg parser

api/python/cell_census/pyproject.toml, api/python/cell_census/tests/test_directory.py
Also added a test to validate the live release directory
=> Python package: update tiledbsoma dep to 1.0.0rc1

api/python/cell_census/pyproject.toml, tools/scripts/requirements.txt
Updates both the Python cell-census package and builder to 1.0.0rc4
=> update to tiledbsoma 1.0.0rc4

api/python/cell_census/pyproject.toml, tools/scripts/requirements.txt
=> Update to tiledbsoma 1.0.0

tools/cell_census_builder/anndata.py, tools/cell_census_builder/tests/anndata/conftest.py, tools/cell_census_builder/tests/anndata/test_anndata.py
Unit test for the `open_anndata` function.
The way I implemented fixtures for this test isn't very elegant but it's functional. Suggestions on how to improve it are welcome.
=> open_anndata unit test

api/python/cell_census/src/cell_census/_experiment.py, api/python/cell_census/src/cell_census/_get_anndata.py, api/python/cell_census/src/cell_census/_open.py, api/python/cell_census/src/cell_census/_presence_matrix.py, api/python/cell_census/src/cell_census/_release_directory.py, docs/conf.py, tools/cell_census_builder/experiment_builder.py, tools/cell_census_builder/util.py
The lifecycle annotations are now using their own directive. This will help when rendering the docs using Sphinx, and they look better in general.
=> Update lifecycle annotations to be consistent with tiledbsoma

api/python/cell_census/pyproject.toml
=> Update Python cell-census package to tiledbsoma 1.2.1

.github/ISSUE_TEMPLATE/feature-request.md
Adds an issue template for users providing a feature request.
=> adds feature request template

api/python/cell_census/tests/README.md, api/python/cell_census/tests/test_acceptance.py
Changes:
1. add additional tests and tune their config
2. use more realistic tiledb config for very large tests
3. tune which tests run in CI
4. Capture the first snapshot of all acceptance tests in the test README.md.
=> acceptance test run

.github/workflows/py-build.yml
=> rename ECR repo

api/python/cellxgene_census/src/cellxgene_census/_get_anndata.py, api/python/cellxgene_census/src/cellxgene_census/_open.py, api/python/cellxgene_census/src/cellxgene_census/_release_directory.py
Modify docstrings to use (new, corrected) package name
=> package name changes in docstrings

api/python/cellxgene_census/pyproject.toml
=> update package metadata to tag maturity as beta

docs/examples.rst, docs/index.rst, docs/python-api.rst, docs/schema.rst, docs/setup.rst, docs/soma.rst
Various updates to the docsite, including name/package changes.
=> Miscellaneous docs updates

docs/cellxgene_census_FAQ.md
=> Adds Census FAQ

api/r/cellxgene.census/_pkgdown.yml, docs/conf.py, docs/generate-r-docs.sh
=> Add plausible to sphinx and pkgdown

README.md, api/python/notebooks/README.md, docs/cellxgene_census_storage_and_release_policy.md
Part of #325 and fixes a few links and typos.
=> Fix naming and links and small editorial changes of documentation.

.github/workflows/r-check.yml, api/r/cellxgene.census/R/get_helpers.R, api/r/cellxgene.census/man/get_seurat.Rd, api/r/cellxgene.census/tests/testthat/test-get_helpers.R
=> refractor get_seurat, update docs and tests

api/python/cellxgene_census/pyproject.toml
=> bump tiledbsoma to 1.2.2

api/python/cellxgene_census/README.md
In preparation of Python v1.0 release. This text is shown on pypi.org cellxgene-census package page.
=> Modify README.md to remove pre-release status

.github/workflows/docsite-build-deploy.yml, docs/README.md
Creates a GHA workflow for building and releasing the docsite automatically.
=> Docsite GHA workflow

docs/_static/css/custom.css, docs/_templates/layout.html
Fixes #403 
Example: https://cellxgene-census.readthedocs.io/en/ebezzi-readthedocs/
Do not merge until Thursday Apr 27
=> Add Census link to docpage navbar

docs/cellxgene_census_docsite_landing.md, docs/cellxgene_census_docsite_quick_start.md, docs/cellxgene_census_docsite_schema.md
Fixes small nits caught after rendering doc-site.
=> [doc-site] Small formatting nit fixes, removes one R example in quick start

docs/cellxgene_census_docsite_FAQ.md, docs/cellxgene_census_docsite_landing.md, docs/cellxgene_census_docsite_quick_start.md, docs/cellxgene_census_docsite_schema.md
Second iteration of changes from comms, see the working doc [here](https://docs.google.com/document/d/1_yZETL72hBD69VJmrQYAaD1iwXj7xCb_aUa6w6ZlUl0/edit)
=> Incorporate comms changes

api/python/notebooks/api_demo/census_gget_demo.ipynb
Hi all, sorry for the second PR. 
I noticed that the Google Colab link was not working anymore since the name and location of the notebook changed, so I edited the following:
- Fixed (hopefully) Google Colab link at the top of notebook
- Noted the gget version when the cellxgene module was first added (under ## Install)
- Added citation guidelines to the first markdown cell
- The text still mentioned an argument that was deprecated (`anndata=False`), so I corrected this to `meta_only=True`
=> A few final edits to gget tutorial

docs/conf.py
Fixes #455 
Also add new notebooks to the docsite
=> Fix docsite version and disable searchbar

api/python/cellxgene_census/pyproject.toml
Update the tiledbsoma dependency to the latest, ==1.2.4
=> pin tiledbsoma==1.2.4

api/python/cellxgene_census/src/cellxgene_census/__init__.py, docs/conf.py, docs/python-api.rst
Adds autosummary to the docs. This originally came from [this ticket](https://github.com/single-cell-data/TileDB-SOMA/issues/1326) on the tiledbsoma project.
=> [docs] Add autosummary

.github/workflows/py-unittests.yml
=> Fix runs-on to use matrix strategy in py-unittests

docs/cellxgene_census_docsite_FAQ.md, docs/cellxgene_census_docsite_installation.md
=> Add Databricks install instructions to FAQ

docs/_templates/layout.html
=> [docs] Fix the Census link in navbar

api/python/cellxgene_census/src/cellxgene_census/experimental/ml/pytorch.py, api/python/cellxgene_census/tests/experimental/ml/test_pytorch.py
=> fix pytorch multiprocessing result

.github/workflows/py-unittests.yml, api/python/cellxgene_census/pyproject.toml, api/python/notebooks/README.md, docs/setup.rst, tools/cellxgene_census_builder/pyproject.toml
=> Add support for Python 3.11

docs/census_notebook_guidelines.md
- Corrects mentions of old feature name "Cell Census"
- Adds symlink information for python notebooks
=> update notebook guidelines

api/python/cellxgene_census/src/cellxgene_census/experimental/ml/pytorch.py, api/python/cellxgene_census/src/cellxgene_census/experimental/pp/_highly_variable_genes.py, api/python/cellxgene_census/src/cellxgene_census/experimental/util/__init__.py, api/python/cellxgene_census/src/cellxgene_census/experimental/util/_csr_iter.py, api/python/cellxgene_census/src/cellxgene_census/experimental/util/_eager_iter.py, api/python/cellxgene_census/tests/experimental/ml/test_pytorch.py
Follow-up work for #575:
- Added unit tests for eager fetching feature of ExperimentDataPipe
- Method rename for privacy, consistency
=> pytorch eager fetch follow-up

api/r/cellxgene.census/R/get_helpers.R, api/r/cellxgene.census/tests/testthat/test-get_helpers.R
=> [r] get_seurat: allow selection of Seurat `counts` or `data` slot

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/manifest.py
=> Update builder to use schema_version param to pin dataset CxG schema versions to 3.0.0

docs/_static/css/custom.css
=> docs: cell guide button beta tag alignment

docs/cellxgene_census_schema.md
this PR fixes a merge error that was present in the Census schema doc.
=> fix merge error in schema doc

.github/workflows/docsite-build-deploy.yml
=> [docs] fetch-depth: 0 for docsite build

.github/workflows/r-check.yml
=> [r] run R tests with both release and latest versions of tiledbsoma

api/python/cellxgene_census/src/cellxgene_census/_release_directory.py, api/python/cellxgene_census/tests/test_directory.py
=> get_census_version_directory returns sorted elements

docs/cellxgene_census_mirroring.md
Resolves lint in a markdown file omitted from PR #721
=> fix markdown lint

api/python/cellxgene_census/pyproject.toml
Updates pinned tiledbsoma version to latest
=> [python] Bump tiledbsoma pinned version to 1.4.3

api/release_process.md
=> [docs] Update API release process to support both R and Python releases

tools/cellxgene_census_builder/entrypoint.sh
For https://github.com/chanzuckerberg/cellxgene-census/issues/744
=> add builder dmesg logging on error

api/python/cellxgene_census/src/cellxgene_census/_get_anndata.py, api/python/cellxgene_census/tests/test_get_anndata.py
=> [python] Add `X_layers` argument to `cellxgene_census.get_anndata()`

.github/workflows/py-dependency-check.yml, README.md
=> [python][misc] GHA for Python dependency checks

.github/workflows/py-dependency-check.yml
The nightly run of this workflow failed due to rate limiting.  Added an authentication token.
=> Add authentication to py-dependency-check workflow

tools/cellxgene_census_builder/src/cellxgene_census_builder/__main__.py
Restores h5ad replication to mirrors.
=> [builder] Restore h5ad replication

.github/workflows/docsite-build-deploy.yml, .github/workflows/py-build.yml, .github/workflows/py-formatting.yml, .github/workflows/py-unittests.yml, .github/workflows/r-check.yml, .pre-commit-config.yaml, api/python/cellxgene_census/tests/test_directory.py
Fixes #827 
Changes:
* Update actions/checkout to v4
* update pre-commit module versions
* fix a bit of lint found by the latest mypy (in unit test code)
=> update GHA action and pre-commit versions

api/python/cellxgene_census/tests/experimental/pp/test_hvg.py
The HVG tests which compare against scanpy are sensitive to numeric instability when batch sizes get small.  Allow for this by increasing batch size and loosening tolerances a bit.
Additionally: there is another error that ScanPy will occasionally raise on failure - catch and skip test.
=> update hvg acceptance tests to account for numerical instability

tools/cellxgene_census_builder/src/cellxgene_census_builder/__main__.py, tools/cellxgene_census_builder/src/cellxgene_census_builder/data_copy.py
Syncs the whole bucket (or better, the `cell-census` directory) instead of the artifact, in delete mode.
=> [builder] Sync whole bucket

docs/cellxgene_census_aws_open_data.md
Amazing project. Happy to start contributing.
Quick two-character typo transposing 'donwload' with 'download'
=> DOC: Update cellxgene_census_aws_open_data.md typo

docs/_static/css/custom.css, docs/_templates/layout.html
#835 
Note: There was an untracked directory added at some point during my doc HTML generation (`_autosummary/`). Should I commit, add to .gitignore, or no action?
=> docs: update header to new design

.github/workflows/py-build.yml, .github/workflows/py-unittests.yml, .pre-commit-config.yaml, tools/cellxgene_census_builder/Dockerfile, tools/cellxgene_census_builder/README.md, tools/cellxgene_census_builder/pyproject.toml
Move the builder and builder docker image to Python 3.11
Fixes #621
=> [builder] move builder to python 3.11

docs/cellxgene_census_docsite_FAQ.md
=> [docs] Fix FAQ link

.pre-commit-config.yaml, api/python/cellxgene_census/src/cellxgene_census/experimental/diffexp/memento/README.md, api/python/cellxgene_census/src/cellxgene_census/experimental/diffexp/memento/diff_expr.py, api/python/cellxgene_census/tests/experimental/diffexp/memento/test_diff_expr.py, tools/models/memento/README.md, tools/models/memento/src/estimators_cube_builder/__main__.py, tools/models/memento/src/estimators_cube_builder/cube_builder.py, tools/models/memento/src/estimators_cube_builder/cube_schema.py, tools/models/memento/src/estimators_cube_builder/estimators.py, tools/models/memento/src/estimators_cube_builder/mp.py
- Migrated code from https://github.com/mincheoly/memento-cxg/blob/atol/codify-and-compare-notebooks/
- Reorganized code to fit this repo, splitting api and builder into api/ and tools/ dirs, repsectively
- Added type hints
- Updated docs (a bit)
This work is still pre-alpha, so for now I have this PR being merged to an epic branch, not `main`.  But could probably do so if nothing added by this PR is deemed objectionable for `main`. 
Reviewers can primarily focus more on the overall structure of the code being added (dirs, classes, naming, etc.), and secondarily review the code itself, which is still a prototype level and for which there is still considerable work to be done to "productionize" it.
=> Migrate memento code (cube builder and diffexp method)

.github/workflows/full-unittests.yml
PR removes the OS package installs that are already installed in the self-hosted docker image.
=> remove OS dependencies from Action workflow

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/util.py
Adds HTTP get retry to the builder where it was missing such logic.  Hardening only - no change in baseline behavior
=> [builder] add http fetch retries

.github/workflows/close-stale-prs.yml, .github/workflows/py-build.yml, .github/workflows/py-dependency-check.yml, .github/workflows/py-formatting.yml
Move an additional 4 workflows to self-hosted runners
=> [misc] move more workflows to self-hosted runners

api/python/cellxgene_census/src/cellxgene_census/experimental/ml/pytorch.py
Fixes #955 
Remove dependency upon a private method that is removed as of tiledbsoma 1.7.0
=> fix pytorch tiledbsoma dependency

api/python/cellxgene_census/src/cellxgene_census/experimental/pp/_highly_variable_genes.py
Partial solution to #953 - use the new threaded indexer in HVG calc
=> [python] use new indexer in highly variable gene algo

tools/models/scvi/scvi-config.yaml, tools/models/scvi/scvi-create-latent-update.py, tools/models/scvi/scvi-prepare.py, tools/models/scvi/scvi-train.py
Changes discussed with the SCVI team.
=> SCVI changes

api/python/cellxgene_census/pyproject.toml
=> Remove upperbound on numpy

api/python/cellxgene_census/src/cellxgene_census/experimental/_embedding.py
Fixes #953 
Update get_embedding to use the parallel indexer
=> [python] update to use tiledbsoma indexer for get_embedding

.github/workflows/py-build.yml
=> [misc] action workflows - update versions of various third party actions

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/globals.py
This is a _possible_ fix for the worker out-of-threads failure occuring after the update to tiledbsoma 1.7.  See single-cell-data/TileDB-SOMA#2149 for details.
Changes: capped the IO and compute parallelism at 32 threads (previously 128), which should reduce the overall allocation on high-CPU boxes (which have many workers).
This is not a "tuned" number, but a first cut guess that can be refined later.
=> [builder] reduce thread counts per worker

tools/cellxgene_census_builder/entrypoint.sh
Additional logging in production container to facilitate thread/map debugging.
=> [builder] log system state in docker prod container entry

tools/models/geneformer/helpers/ontology_mapper.py
fixes CL_0002494 from cell class to cell subclass https://czi-sci.slack.com/archives/C023Q1APASK/p1708047974696449?thread_ts=1707952513.995039&cid=C023Q1APASK
=> [misc] Fix CL_0002494 in geneformer pipeline

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/experiment_builder.py, tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/globals.py, tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/tissue_mapper.py, tools/cellxgene_census_builder/tests/test_tissue_mapper.py
=> [builder] update uberon and tissue_general mapping to schema 4 standard

api/python/cellxgene_census/src/cellxgene_census/_get_anndata.py, api/python/cellxgene_census/src/cellxgene_census/_open.py, api/python/cellxgene_census/src/cellxgene_census/experimental/_embedding.py, api/python/cellxgene_census/src/cellxgene_census/experimental/ml/pytorch.py, api/python/cellxgene_census/src/cellxgene_census/experimental/pp/_highly_variable_genes.py, api/python/cellxgene_census/src/cellxgene_census/experimental/pp/_stats.py, docs/_static/css/custom.css, docs/conf.py
- Fixes intersphinx bindings for tiledbsoma
- Adds more intersphinx bindings (scanpy, torch, etc)
- Fix wrong formatting
- Other misc fixes (typos, dates, etc).
- Updates copyright
This has been tested locally and the docsite renders correctly.
=> [docs] misc docsite adjustments

.github/workflows/r-dependency-check.yml
Fixes #990
Tested: https://github.com/chanzuckerberg/cellxgene-census/actions/runs/8197952436
=> [R] fix R dependency check workflow

docs/_static/css/custom.css
For some reason, the CSS file was linted and that caused issues with the navbar. Reverting those changes.
=> [docs] Revert bad CSS changes

api/r/cellxgene.census/DESCRIPTION
=> [misc] Prepare release 1.11.1

tools/cellxgene_census_builder/tests/test_builder.py
=> [builder] fix test hang

.github/workflows/r-check.yml, api/r/cellxgene.census/tests/testthat/acceptance-tests.R
Issue is known to the TileDB team and might have user impact. For now, this will unblock our CI/CD.
=> [R] Pin R TileDB to 0.24

tools/cellxgene_census_builder/pyproject.toml
Update Builder dependency to tiledbsoma==1.9.3 to take advantage of small performance improvement
=> [builder] bump Builder tiledbsoma version

api/python/cellxgene_census/src/cellxgene_census/experimental/pp/_highly_variable_genes.py, tools/cellxgene_census_builder/tests/test_numeric.py
Additional unit tests to cover float precision reduction in more detail
=> [builder] add unit test for float precision reduction

docs/cellxgene_census_schema.md, docs/census_accepted_assays.csv, tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/globals.py
=> Update list of accepted assays and bump schema to 2.0.1

.github/workflows/lts-compat-check.yml, .github/workflows/py-dependency-check.yml
=> [python] Fix git-lfs issue when cloning Geneformer in other places

.github/workflows/py-unittests.yml
Adding a step to CI where the installed versions of dependencies are reported all in one place
=> report installed versions

api/python/cellxgene_census/src/cellxgene_census/experimental/pp/_highly_variable_genes.py
Temporary fix for https://github.com/single-cell-data/TileDB-SOMA/issues/2653 until a permanent solution is found.
=> [python] Remove new indexer from hvg

api/r/cellxgene.census/README.md
=> Fix links in R README.md

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/experiment_builder.py
This function doesn't return a Dask collection
=> [builder] Correct docstring in builder

docs/conf.py
=> [docs] Fix doc versions

tools/cellxgene_census_builder/pyproject.toml
Towards #1243
Pending discussion in that issue on just jumping straight to 1.12
=> [builder] Bump tiledbsoma dep to 1.11.4 in the builder

docs/cellxgene_census_docsite_data_release_info.md
=> [docs] Fix date on `cellxgene_census_docsite_data_release_info.md`

docs/_templates/layout.html
=> feat: Update navbar to include Differential Expression

api/python/cellxgene_census/tests/experimental/pp/test_online.py
Fix the mypy error we're currently seeing. Should be merged right after spec-0 PR (#1189) so that the typing syntax is supported
=> [python] Fix mypy error

api/python/cellxgene_census/pyproject.toml
=> [python] Pin against tiledbsoma 1.14.1

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/globals.py
=> Add newly approved assays

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/experiment_builder.py, tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/globals.py, tools/cellxgene_census_builder/tests/conftest.py
Fixes #1301 
I believe this is all that's necessary to include the `feature_type` column to `var`.
=> Add feature_type column to var

docs/cellxgene_census_docsite_landing.md
Adding a warning to the docsite about spatial
=> Add warning about tiledbsoma library update to docsite

api/python/cellxgene_census/pyproject.toml
=> Bump tiledbsoma pin to >=1.15.3

api/python/cellxgene_census/pyproject.toml
Make it possible to do `pip install "cellxgene_census[spatial]"`
=> Add 'spatial' extra install

.github/workflows/py-unittests.yml, api/python/cellxgene_census/scripts/requirements-dev.txt
Fixing https://github.com/chanzuckerberg/cellxgene-census/actions/runs/13281375913/job/37214045424#step:7:300
=> fix: update Geneformer version installed in CI

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/build_soma.py, tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/globals.py, tools/cellxgene_census_builder/tests/test_spatial.py
=> Allow duplicates in spatial coordinates

.github/workflows/py-unittests.yml
=> Remove pytest run with numba disabled

docs/examples.rst
=> Fix spelling of accessing

api/python/cellxgene_census/src/cellxgene_census/_experiment.py, api/python/cellxgene_census/src/cellxgene_census/_get_anndata.py, api/python/cellxgene_census/src/cellxgene_census/_presence_matrix.py, api/python/cellxgene_census/tests/test_get_anndata.py, api/python/cellxgene_census/tests/test_get_helpers.py
Implementing the first part of https://github.com/chanzuckerberg/cellxgene-census/issues/1359
=> Add support for getting data from census_spatial_sequencing to get_anndata, get_obs, get_var

docs/census_accepted_assays.csv, docs/census_accepted_assays_full_gene.csv, tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/globals.py
=> Update accepted assays csv

.github/workflows/docsite-build-deploy.yml, .github/workflows/full-unittests.yml, .github/workflows/profiler.yml, .github/workflows/py-build.yml, .github/workflows/py-dependency-check.yml, .github/workflows/py-formatting.yml, .github/workflows/py-unittests.yml
Merge after https://github.com/chanzuckerberg/gh-self-hosted-runners/pull/52 is merged
=> chore: update runs-on label to use drop-in replacement

dev-docs/cellxgene_census_draft_schema.md
There will be further editorial updates throughout the document. This focuses on the basic changes for changes in organism requirements to unblock @mlin on initial iterations. It also updates CELLxGENE schema references to 7.0.0 and includes minor editorial changes. 
Closes #1406
=> Updated organism requirements
