.github/workflows/formatting.yml
api/python/cell_census/setup.cfg
api/python/cell_census/src/cell_census/__init__.py
api/python/cell_census/src/cell_census/experiment_query/query.py
api/python/cell_census/src/cell_census/get_anndata.py
api/python/cell_census/src/cell_census/open.py
api/python/cell_census/src/cell_census/release_directory.py
api/python/cell_census/tests/test_directory.py
api/python/cell_census/tests/test_util.py
cell_census_builder/experiment_builder.py
cell_census_builder/validate.py

Changes:
* missing yield causes get_anndata to fail on empty query.  Change made to experiment_query.query.py.  Fixes #26
* cell-census schema requires no explicitly stored zeros. Add code to enforce _and_ validate this.  Fixes #23 
* add a couple of small unit tests to kick-start efforts to build full set of unit tests. A start at #9   Includes change to formatting.yml GH Action definition required to perform static type analysis on the unit tests.
* add docstrings to cell_census pubilc API.  Fixes #15 
* add missing type declaration for new tissue_general columns. Fixes #20 
* Fixed cell_census package dependencies to allow for the _pre-release_ version of tiledbsoma

miscellaneous small fixes

---

.github/workflows/formatting.yml
api/python/cell_census/setup.cfg
api/python/cell_census/src/cell_census/compute/meanvar.py
api/python/cell_census/src/cell_census/experiment_query/axis.py
api/python/cell_census/src/cell_census/experiment_query/query.py
api/python/cell_census/src/cell_census/experiment_query/types.py
api/python/cell_census/src/cell_census/get_anndata.py
api/python/cell_census/src/cell_census/release_directory.py
cell_census_builder/REAMDE.md
cell_census_builder/__main__.py
cell_census_builder/anndata.py
cell_census_builder/consolidate.py
cell_census_builder/experiment_builder.py
cell_census_builder/globals.py
cell_census_builder/manifest.py
cell_census_builder/validate.py

Changes:
* added hooks for using platform_config to tune Census schema (i.e., do not use default SOMA schema)
* first round of schema tuning - primarily filter pipeline configuration
Unrelated, small changes:
* broaden Python versions supported (changes to type static typing and type checks in the GH action)
* parallelize consolidation pass to reduce build time
* disallow python 3.11 support until numba is updated

schema performance tuning

---

api/python/cell_census/src/cell_census/experiment_query/query.py
cell_census_builder/consolidate.py
cell_census_builder/experiment_builder.py
cell_census_builder/validate.py
docs/cell_census_schema_0.0.1.md

SOMA API name change  `s/NdArray/NDArray/g`  - rippled through the cell_census package.
See single-cell-data/TileDB-SOMA#608

accommodate SOMA API name changes

---

.github/workflows/unittests.yml
api/python/cell_census/README.md
api/python/cell_census/scripts/requirements-dev.txt
api/python/cell_census/setup.cfg
api/python/cell_census/src/cell_census/__init__.py

Changes:
* Pin the cell_census package dependency for tiledbsoma to 0.5.0a2
* Set the supported python versions (in setup.cfg) to Python 3.8-3.10.  3.11 not supported yet due to numba, and python 3.7 not supported due to tiledbsoma.
* Fix & enable the  unit test workflow for Python matrix [Linux, MacOS] X [Py3.8, Py3.9, Py3.10]
* change package version to 0.0.1-rc0

Refine unit test workflows

---

docs/cell_census_schema_0.0.1.md

Changed link for census metadata fields that are from the Data Portal by linking out to the [Discover API schema docs](https://api.cellxgene.cziscience.com/curation/ui/). This API's schema docs will have a data model diagram for an overview, once we deploy https://github.com/chanzuckerberg/single-cell-data-portal/pull/3844 to prod. The API schema docs already have specific definitions for most of the fields being referenced (in the "Schemas" section), which should be sufficient. We can enhance the field descriptions as needed.

docs: update link to Discover API schema docs

---

api/python/cell_census/src/cell_census/presence_matrix.py
api/python/notebooks/analysis_demo/comp_bio_explore_and_load_lung_data.ipynb
api/python/notebooks/analysis_demo/comp_bio_normalizing_full_gene_sequencing.ipynb

Update the Python API and notebooks to look for the presence matrix in the new location.
Partially addresses #60 
Related to #69 and #66
NOTE: all unit tests against the live corpus will fail until a new data build is available.

presence matrix location change in schema 0.2.0

---

tools/cell_census_builder/manifest.py
tools/cell_census_builder/scripts/aws/mount_instance_storage.sh
tools/cell_census_builder/scripts/aws/swapon_instance_storage.sh
tools/cell_census_builder/util.py

* slow down API requests to avoid DOS'ing Discover API (temporary fix)
* remove reading of tombstone attribute in API response (no longer exists)
* aws scripts allow parameterization of which disk devices to use: `swap_instance_storage.sh` takes a count, while `mount_instance_storage.sh` takes list of actual devices (can be improved)

builder fixes

---

api/python/cell_census/pyproject.toml
tools/scripts/requirements.txt

This partially addresses a bug whereby builder ("writer") can potentially create a census with a TileDB on-disk format that is incompatible with the TileDB version used by the API ("reader"), due to it being ahead of the reader's version. The change here only ensures that Cell Census components are using the same version of TileDB used by TileDB-SOMA. An additional fix is needed in TileDB-SOMA to ensure that the TileDB version it uses to write data is always <= the TileDB version it usese to read data.
Changes:
- Use the same tiledb version as tiledbsoma to ensure read/write compatibility with on-disk TileDB formats
- Add notes about tiledbsoma version constraints between Builder and API

tiledb version dependency fixes

---

api/python/notebooks/api_demo/census_axis_query.ipynb
api/python/notebooks/api_demo/census_compute_over_X.ipynb

Fix two typos in the `census_axis_query.ipynb` notebook.

fix: typos in census_axis_query.ipynb

---

tools/cell_census_builder/__main__.py
tools/cell_census_builder/consolidate.py
tools/cell_census_builder/mp.py

Changes:
* reduce the consolidation buffer per TileDB guidance.  Has effect of removing the excessive memory contention which was causing very long build times.  With this change, we are back to a 6-7 hour build (tested on a c6id.32xlarge with filesystem on EBS).
* added soma buffer config which was missing
* fixed a process return value bug which caused successful runs to return a process code of 1 rather than the intended 0
Fixes #86

census builder performance fixes

---

tools/cell_census_builder/__main__.py
tools/cell_census_builder/globals.py
tools/cell_census_builder/util.py
tools/cell_census_builder/validate.py
tools/scripts/requirements.txt

Adds the git commit SHA field to the `metadata` object of the top level collection.
Tested by running a local build of the census and inspecting the result

Add git SHA to the metadata field of census

---

api/python/cell_census/src/cell_census/get_anndata.py

Because the census has a single index dimension on both axis, we can further refine the get_anndata parameters for simplicity, by assuming a single dim.
Fixes #119

Coords param change for get_anndata

---

.github/workflows/unittests.yml
api/python/cell_census/README.md
api/python/cell_census/pyproject.toml
api/python/cell_census/src/cell_census/__init__.py

With this PR, we now support Python versions 3.7 to 3.10.
Python 3.11 support is pending numba support for the same.
Fixes #120

Add Python 3.7 support

---

tools/cell_census_builder/util.py

This allows to run the builder from any subdirectory (including `tools`).

Add parent directory check for git.Repo

---

tools/cell_census_builder/manifest.py

Fixes #161 
Changes:
Remove parsing of dataset_title from Discover API collection response; the attribute is not provided there; it is provided in the individual responses made for each dataset
Testing:
Tested 1-line code removal earlier on EC2 instance. Did not test this change again after making the PR, but upcoming census build will confirm.
Did NOT add a test, as this was done in another [issue](https://github.com/chanzuckerberg/cell-census/issues/111) that more thoroughly tests.

fix: builder no longer expects dataset_title in collection response

---

tools/cell_census_builder/scripts/release/census_summary.py

The `census_summary` script can now be used to generate a diff
Example usage: 
```python -m tools.cell_census_builder.scripts.release.census_summary -c 2023-02-06 diff -p 2023-01-30```
Example output:
```
Datasets that were added
d7d7e89c-c93a-422d-8958-9b4a90b69558
3c75a463-6a87-4132-83a8-c3002624394d
5500c673-1610-40a0-86d9-64d987ae50e6
a5d95a42-0137-496f-8a60-101e17f263c8
Previous homo_sapiens cell count: 43246174, current homo_sapiens cell count: 43420131, delta 173957
Previous mus_musculus cell count: 3922090, current mus_musculus cell count: 3922090, delta 0
```
Other cases are computed but only displayed if the difference is not null.

Report cell census changes between versions

---

tools/cell_census_builder/scripts/release/census_summary.py

Fixes #172 
Note to reviewer:  pandas-stubs and the Pandas docs differ, and there are legal values (used in this code) which are not accepted by the pandas-stubs type signatures.

lint in census_summary

---

api/python/notebooks/analysis_demo/comp_bio_query_data_and_metadata.ipynb
docs/cell_census_schema.md

Changes:
- Clarifies 'Feature Dataset Presence Matrix' specification, it was recently noted by @atolopko-czi that the spec was ambiguous and text was added to clarify it
- The schema minor version is bumped.
- Removes version number from schema file to reduce maintenance cost of other docs referring to it.

docs: Clarifies text for Feature Dataset Presence Matrix, rename schema file

---

tools/cell_census_builder/globals.py

enable duplicates for performance

---

tools/cell_census_builder/__main__.py
tools/cell_census_builder/experiment_builder.py
tools/cell_census_builder/tests/test_builder.py

Reverts a [change](https://github.com/chanzuckerberg/cell-census/commit/85bf654ebdfae67a64135b086a078b27bf041715#diff-32913cbb027d8f5e52f9ab54e24145dcb765c97d8ad2e6165e45625fade18e39R268) that introduced a bug that led the presence matrix to have an incorrect shape.
Per [the cell-census schema specification](https://github.com/chanzuckerberg/cell-census/blob/main/docs/cell_census_schema.md#feature-dataset-presence-matrix--census_objcensus_dataorganismmsrnafeature_dataset_presence_matrix--somasparsendarray), the presence matrix needs to have N rows where N is the number of datasets belonging to the experiment. Since this is a sparse matrix, its _domain_ will extend to the total number of datasets (i.e. `max(d.soma_joinid for d in datasets)`), therefore the shape of the presence matrix (for …

fix presence matrix wrong shape

---

api/python/cell_census/src/cell_census/_experiment.py
api/python/cell_census/src/cell_census/_get_anndata.py
api/python/cell_census/src/cell_census/_open.py
api/python/cell_census/src/cell_census/_presence_matrix.py
api/python/cell_census/src/cell_census/_release_directory.py
docs/conf.py
docs/python-api.rst

Notes: 
1. The docstrings at the beginning of each module could use some work. That said, the modules generally only contain 1-2 functions, and the examples are defined in the functions.
2. I removed type annotations from `Args`. They are only recommended if the functions lack type annotations, which is not our case. I think removing them helps with the readability, but we can add them back.

Change docstrings to use Google conventions

---

tools/cell_census_builder/__main__.py
tools/cell_census_builder/datasets.py
tools/cell_census_builder/experiment_builder.py
tools/cell_census_builder/tests/conftest.py
tools/cell_census_builder/tests/test_builder.py
tools/cell_census_builder/validate.py
tools/scripts/requirements.txt

Fixes #215 
Fixes #179 
Changes:
* Break the ExperimentBuilder into two parts:
* ExperimentSpecification - read-only declaration of Experiment configuration.  May not contain information derived from the AnnData files.
* ExperimentBuilder - the accumulated state used during the build process, derived from AnnData input files.
* Refactor the validator to _only_ use the ExperimentSpecifications, increasing isolation from the build process. As a side effect, this fixes #179
* Minor fixes to test_builder which was incorrectly creating AnnData's (this cleans up all of the warnings generated during the test execution)
* Added `attrs` dependency (preferred over dataclasses, and used to create ExperimentSpecification)

refactor ExperimentBuilder and validator for improved validator isolation

---

api/python/cell_census/tests/test_directory.py
api/python/cell_census/tests/test_get_helpers.py
api/python/cell_census/tests/test_open.py
api/python/cell_census/tests/test_util.py

Changes - more/better unit tests for the cell_census python package:
* add error condition unit test coverage for `open_soma` and other API
* add tests to cover all `open_soma` parameters
* add missing absolute URI test for `uri_join`

add unit tests for python cell_census package

---

.github/workflows/py-build.yml
.github/workflows/py-formatting.yml
.github/workflows/py-unittests.yml
.github/workflows/r-check.yml

I must have goofed these originally.

[ci] fix paths-ignore in workflow YMLs

---

tools/cell_census_builder/validate.py

Proposed revision to test full contents of the X matrix in validation pass, plus presence contents.
Tested on a full census build, on the standard config, and it ran 5 hrs 10 minutes.

X contents validation

---

tools/cell_census_builder/mp.py

Adding assertion to the process pool creation utility to confirm that the system is correctly configured. This will prevent chasing of obscure bugs on systems which default to `fork` rather than `spawn`

assertion to confirm correct MP configuration

---

tools/cell_census_builder/experiment_builder.py
tools/cell_census_builder/tests/test_util.py
tools/cell_census_builder/util.py

Unit tests for:
- `is_positive_integral`
- `array_chunker`
- `uricat`

Util unit tests

---

api/python/cell_census/pyproject.toml

Partial fix for #280 
This fixes package metadata for the Python cell-census package.

fix email address in Python package metadata

---

api/python/cell_census/pyproject.toml

Fixes #336 
Changes to the dependencies for `cell-census` python package:
* remove unused/unnecessary packages (scikit-misc, numba)
* added missing package (scipy)
* changed order & constraints on numpy to allow the old pip solver to correctly determine version required

clean up dependencies for cell_census

---

README.md
api/python/cellxgene_census/src/cellxgene_census/_open.py
api/python/cellxgene_census/src/cellxgene_census/_release_directory.py
api/python/cellxgene_census/tests/README.md
api/python/cellxgene_census/tests/test_acceptance.py
tools/cellxgene_census_builder/README.md
tools/cellxgene_census_builder/src/cellxgene_census_builder/__main__.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/__main__.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/datasets.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/census_summary.py
tools/cellxgene_census_builder/tests/test_builder.py

Fixes #319 
This changes the name of cell census to cellxgene census in all docstrings/md files except the schema spec.

update cell census name in docstrings/md files

---

api/r/cellxgene.census/R/open.R
api/r/cellxgene.census/R/source_h5ad.R
api/r/cellxgene.census/tests/testthat/test-release_directory.R

cf. https://github.com/single-cell-data/TileDB-SOMA/commit/8691ce07da3847eb5a31830deb30593181165738
also incidentally fix deferred FIXME regarding UTF-8 error in value_filter

[r] use new SOMATileDBContext$context() accessor

---

README.md

Small fix to send users to doc-site instead of github

chore: fix link to tutorials in README

---

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/datasets.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/manifest.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/source_assets.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/validate_soma.py
tools/cellxgene_census_builder/tests/anndata/conftest.py
tools/cellxgene_census_builder/tests/conftest.py
tools/cellxgene_census_builder/tests/test_manifest.py
tools/cellxgene_census_builder/tests/test_source_assets.py

Use GET /datasets endpoint for builder

---

docs/cellxgene_census_schema.md

Part of #325 and it also adds pending information to the schema.
All changes include:
* Updates text to reflect official name: CZ CELLxGENE Discover Census.
* Updates `census["census_info"]["summary"]` to reflect official name in the column `label`:
* From `"cell_census_build_date"` to `"census_build_date"`.
* From `"cell_census_schema_version"` to `"census_schema_version"`.
* Adds the following rows to `census["census_info"]["summary"]`:
* `"census_build_git_commit_sha"`
* `"census_r_api_version"`
* `"census_python_api_version"`
@atolopko-czi  please take close attention to the new rows added to the `"summary"` data frame

Updates schema to 1.0 

---

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/experiment_builder.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/globals.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/tissue_mapper.py

Fixes #355 
Testing is just unit tests, but these load the real ontology file, so should be sufficient.

chore: pin uberon ontology version

---

api/r/cellxgene.census/vignettes/census_query_extract.Rmd

To match #377
PREVIEW: https://gistpreview.github.io/?2136b81605228ca9652b877fffd65424

[r] revise census_query_extract.Rmd

---

api/python/cellxgene_census/src/cellxgene_census/_release_directory.py
api/r/cellxgene.census/R/release_directory.R

Stable route for release.json

---

api/python/cellxgene_census/pyproject.toml
api/python/cellxgene_census/src/cellxgene_census/_open.py

Fixes #414 
Tested on Mac OSX 13.3.1 M1 via local pip install of Python API and use of open_soma() call.

Fix for Mac OSX certificate issue

---

api/python/cellxgene_census/src/cellxgene_census/_open.py
api/python/cellxgene_census/src/cellxgene_census/_release_directory.py
api/python/cellxgene_census/tests/test_directory.py
api/python/cellxgene_census/tests/test_open.py

Resolves #433 
- default to stable release
- notify user when an alias is used
- notify user if stable alias is not defined
New output looks like:
```
import cellxgene_census as cc
c = cc.open_soma()
The "stable" Census version is not yet available. Using "latest" Census version instead.
The "latest" release is currently 2023-04-25. Specify 'census_version="2023-04-25"' in future calls to open_soma() to ensure data consistency.
c = cc.open_soma(census_version="stable")
The "stable" Census version is not yet available. Using "latest" Census version instead.
The "latest" release is currently 2023-04-25. Specify 'census_version="2023-04-25"' in future calls to open_soma() to ensure data consistency.
c = cc.open_soma(census_version="latest")
The "latest" release is currently 2023-04-25. …
```

open_soma() alias handling changes

---

api/python/cellxgene_census/pyproject.toml
api/python/cellxgene_census/src/cellxgene_census/_release_directory.py

Primary change:  pin the tiledb version dependency to >=0.21.3 to account for a missing dependency in tiledbsoma==1.2.2.  See single-cell-data/TileDB-SOMA#1322 for details.   This work-around can be removed when the issue is resolved upstream, and we bump our tiledbsoma pin.
Secondary change:  reverted the URL change for the release.json bootstrap file, introduced in #443.  This will be further updated when the final permalink, and infra changes to support that permalink, are in place.
NOTE:  this PR did not revert the R bootstrap URL.  That needs to be done at some point before it is released. CC: @mlin and @pablo-gar

Pin tiledb version as work-around

---

api/python/cellxgene_census/src/cellxgene_census/_release_directory.py
api/r/cellxgene.census/R/release_directory.R

The Python and R packages are updated to use the public permalink URL for the release directory bootstrap.

update release bootstrap URL to public permalink

---

api/r/cellxgene.census/tests/testthat/test-release_directory.R

The `2023-04-04` version that was pinned in the tests is expired, so this test is now failing. When an LTS version is available, we should switch to that.

Bump static census version in R tests

---

.github/workflows/py-unittests.yml
api/python/cellxgene_census/pyproject.toml
api/python/cellxgene_census/tests/README.md
api/python/cellxgene_census/tests/conftest.py
api/python/cellxgene_census/tests/experimental/ml/test_pytorch.py
api/python/cellxgene_census/tests/test_open.py

This is a sub-branch on `atol/pytorch-dataloader`, to segregate these changes in a separate PR for easier review.
Changes:
- pytest can now also be run with `--experimental` option to explicitly enable tests on the `experimental` sub-package (ie in addition to the `--expensive` option)
- GHA build only runs experimental tests for Python 3.10 to avoid some missing experimental code pkg dependencies for lower Python versions (torch==2.0.1 not avail for Python 3.7)
- fix bug where `pytest -m 'not live_corpus' --experimental` not working

run experimental tests conditionally

---

api/python/cellxgene_census/src/cellxgene_census/_experiment.py
api/python/cellxgene_census/src/cellxgene_census/_get_anndata.py
api/python/cellxgene_census/src/cellxgene_census/_open.py
api/python/cellxgene_census/src/cellxgene_census/_presence_matrix.py
api/python/cellxgene_census/src/cellxgene_census/_release_directory.py
api/python/cellxgene_census/src/cellxgene_census/experimental/ml/__init__.py
api/python/cellxgene_census/src/cellxgene_census/experimental/ml/pytorch.py
api/python/notebooks/ml_demo/pytorch_lr_classifier.py

* Changes existing Python API methods' lifecycle tags to `maturing`
* Sets `experimental` package methods' lifecycle tags to `experimental`
* Adds some documentation to `experimental` public classes and methods, with proper formatting for github pages output.
* Exports public names for `experimental.ml` package
Resolves #508 
Partially addresses: #500

chore: update lifecycle tags

---

api/python/cellxgene_census/pyproject.toml

- bump to 1.2.5, which includes updated api doc lifecycle tags
Follow-up to #508

bump python api tiledbsoma version

---

.github/workflows/py-unittests.yml
api/python/cellxgene_census/src/cellxgene_census/experimental/ml/pytorch.py

fix: pytorch unit test hangs

---

.pre-commit-config.yaml
api/python/cellxgene_census/tests/test_open.py
tools/cellxgene_census_builder/pyproject.toml
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/experiment_builder.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/util.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/util.py

The mypy pre-commit hooks for the builder were broken.  This fixes them, and fixes a bunch of lint I found in the Python code while doing this work.
This also fixes several new errors caught by more recent versions of Ruff.
We need a regular chore to run `pre-commit autoupdate`
*Note to reviewers:* this PR is stacked on the HVG notebook PR #536.    When approved, I'll update that PR, and then merge them together.
changes:
* update pre-commit hooks to latest versions
* add explicit `attrs` dependency for mypy, as it has a built-in extension enabled by this config
* fix various real lint / deprecation found after this update.

pre-commit config update and fixes for resulting lint

---

api/python/cellxgene_census/tests/experimental/ml/test_pytorch.py

Fixes #540. Though "fixes" is a generous term here, since the test is simply skipped for Python 3.9, which appears to be the only Python version affected by this problem.

fix OOM on pytorch unit test

---

.github/workflows/py-unittests.yml

Temporarily remove Python 3.7 on MacOS testing due to a bug. Revert when https://github.com/actions/setup-python/issues/682 is fixed.

Fix MacOS failing tests

---

api/python/cellxgene_census/src/cellxgene_census/experimental/ml/pytorch.py

Partially resolves #524
- Make `_open_experiment()` into a context manager
- Iterate through `_ObsAndXIterator` using a generator, so that `Experiment` can be closed at end of iteration.
Branched off of `524-pytorch-reuse-obs-joinids`.

Close soma handles in ExperimentDataPipe

---

api/python/cellxgene_census/src/cellxgene_census/experimental/ml/pytorch.py
api/python/cellxgene_census/tests/experimental/ml/test_pytorch.py

Uncovered a bug during work on #524. When a PyTorch batch spans multiple SOMA batches, the PyTorch batch size was too large.  
- Fixes bug, adds test
- Refactors `obs_batch` property to `next_soma_batch` method, removing its object side-effects. This makes testing easier and simplifies design.
Branched off of `524-pytorch-reuse-obs-joinids`.

fix batch size bug

---

api/python/notebooks/experimental/pytorch.ipynb

Fixes top-level header which will correct indentation in doc-site:

Correct pytorch notebook header

---

.pre-commit-config.yaml
api/python/cellxgene_census/src/cellxgene_census/experimental/ml/pytorch.py
api/python/cellxgene_census/tests/experimental/ml/test_pytorch.py
api/python/cellxgene_census/tests/experimental/pp/test_hvg.py

Partially resolves #524 
- In multiprocessing mode, if `ExperimentDataPipe` has been initialized prior to creating the child processes, each child process will receive a fully initialized object and the ExperimentAxisQuery and encoders do not need to be re-initialized.
- In particular, the full (unpartitioned) `_obs_joinids` array is cached and now partitioned for each child process at the time of `_ObsAndXIterator` instantiation.  In multiprocessing this should allow the PyArrow-backed soma_joinids to be memory-shared across child processes, without having to serialize the array.
- These changes also result in some code simplifications. Since the obs soma_joinids, var soma_joinds from ExperimentAxisQuery are directly cached, rather than the entire ExperimentAxisQuery object itself, the …

Avoid unnecessary re-initialization of ExperimentDataPipe in mp mode

---

api/python/cellxgene_census/pyproject.toml

I ran into the following error when trying to use the `download_source_h5ad` function after installing `cellxgene_census` via `pip` (version 1.2.1):
```txt
>>> cellxgene_census.download_source_h5ad("9d8e5dca-03a3-457d-b7fb-844c75735c83", to_path="/mnt/scratch/liurenmi/cellxgene/test.h5ad")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/mnt/home/liurenmi/software/anaconda3/envs/scgsp/lib/python3.9/site-packages/cellxgene_census/_open.py", line 226, in download_source_h5ad
fs = s3fs.S3FileSystem(
File "/mnt/home/liurenmi/software/anaconda3/envs/scgsp/lib/python3.9/site-packages/fsspec/spec.py", line 54, in __call__
obj = super().__call__(*args, **kwargs)
File "/mnt/home/liurenmi/software/anaconda3/envs/scgsp/lib/python3.9/site-packages/s3fs/core.py", line 187, …
```

require s3fs>=2021.06.1 where cache_regions kwarg is added

---

.github/workflows/r-check.yml

Install the latest tiledbsoma from github, while we're still finalizing the r-universe release process: https://github.com/single-cell-data/TileDB-SOMA/issues/1427

[r] install tiledbsoma from github

---

.github/workflows/py-unittests.yml
api/python/cellxgene_census/pyproject.toml
api/python/cellxgene_census/src/cellxgene_census/__init__.py
api/python/notebooks/README.md
docs/cellxgene_census_docsite_installation.md
docs/setup.rst
tools/cellxgene_census_builder/pyproject.toml
tools/pyproject.toml

Fixes #577 
Fixes #564 
Changes:
* Remove support for Python 3.7
* Update tiledbsoma pin to 1.2.7 (latest)
* Pins scipy version to work around pyarrow incompat with latest

Remove python 3.7 support

---

api/python/cellxgene_census/tests/experimental/pp/test_hvg.py

Modify the experimental unit tests to use less memory.  This resolves failures in the GHA CI workflow

use less mem for hvg tests

---

api/python/cellxgene_census/src/cellxgene_census/experimental/util/__init__.py
api/python/cellxgene_census/src/cellxgene_census/experimental/util/_csr_iter.py
api/python/cellxgene_census/tests/experimental/util/test_csr_iter.py
tools/cell_dup_check/finddups.ipynb

Add a new experimental API to iterate over X array returning Scipy sparse CSR or CSC matrix.
Update the finddups notebook to use it
Prototype for single-cell-data/TileDB-SOMA#1503

add sparse iterator to experimental.utils

---

tools/cellxgene_census_builder/pyproject.toml
tools/cellxgene_census_builder/src/cellxgene_census_builder/census_summary.py

Fixes #581 
Fixes #418 
Pin all builder dependencies (excluding two system packages where there is little value).
This ensures that we use the same package versions for test (GHA and manual) and the docker image.

pin builder dependencies

---

docs/python-api.rst

Adds sparse iter reference docs to doc-site

---

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/anndata.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/build_soma.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/manifest.py
tools/cellxgene_census_builder/tests/test_manifest.py

Fixes #606 
Changes:
* if the response from the upstream curation API is suspect, error out.  Do not silently ignore and move on.
* where we were logging as an Error, but it was really a Warning, change log level
* raise RuntimeError in cases of intentionally "bailing" rather than raising AssertionError (save that for assertions)
* fix unit test to match new (expected) behavior

change error handling for /curation REST errors

---

api/python/cellxgene_census/tests/README.md
api/python/cellxgene_census/tests/test_acceptance.py
api/r/cellxgene.census/tests/README.md
api/r/cellxgene.census/tests/testthat/ListReporterToFile.R
api/r/cellxgene.census/tests/testthat/acceptance-tests-run-script.R
api/r/cellxgene.census/tests/testthat/acceptance-tests.R
api/r/cellxgene.census/tests/testthat/helper-acceptance.R
api/r/cellxgene.census/tests/testthat/helper-open_soma.R

- Addresses #190 
- Also updates python acceptance tests:
- Decomposes certain "parametrized" tests into individual test -- this allows for easy 1:1 running time comparisons to R tests.
- Adds a few tests to increase granularity in reading logs

Add R acceptance tests, update Python acceptance tests

---

api/python/cellxgene_census/src/cellxgene_census/experimental/ml/pytorch.py
api/python/cellxgene_census/tests/experimental/ml/test_pytorch.py
api/python/notebooks/experimental/pytorch.ipynb
docs/README.md

Resolves #500
Introduces #614 :)
* Fleshes out docstrings for ExperimentDataPipe et. al.
* Fixes & re-runs pytorch notebook
* Removes testing-only `__main__` from `pytorch.py`
* Rename `{,_}ObsAndXSOMABatch` to indicate it's private

Complete docstrings for PyTorch ExperimentDataPipe API

---

api/python/cellxgene_census/src/cellxgene_census/_open.py

Fixes #622 
Changes:
* consistently set default `census_version` to `stable` throughout the API
* update the docs where they incorrectly indicated the default was `latest`

consistently set default census version to stable

---

api/python/cellxgene_census/tests/test_open.py

Unit test fix for the sporadically broken python package unit tests
Related to the changes made in #623

add missing census_version param

---

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/anndata.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/manifest.py
tools/cellxgene_census_builder/tests/anndata/test_anndata.py
tools/cellxgene_census_builder/tests/test_manifest.py

This PR tightens up error detection for a "should never happen" case where we receive an unsupported CxG schema version in an H5AD file.  The previous behavior was to log a warning and drop the dataset.  The new behavior is to fail the build.
There are no cases of such warning in the logs for the past few weekly builds, and our process is such that it should not occur. This is just an additional sanity check.

hard error if the builder receives an unsupported CXG schema version

---

tools/cellxgene_census_builder/src/cellxgene_census_builder/__main__.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/release_cleanup.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/release_manifest.py
tools/cellxgene_census_builder/tests/test_release_cleanup.py
tools/cellxgene_census_builder/tests/test_release_manifest.py
tools/cellxgene_census_builder/tests/test_workflow_steps.py

Related to #242 
Adds a new flag to the release.json format:  `do_not_delete`.  If set to a true-ish value, will prevent the automated build process from garbage collecting a build.  This is intended for use in protecting LTS releases (when the LTS is tagged, this flag should be set on the build).
If the flag is not set, or is false-ish, the build will be subject to the standard test build cleanup.

add do_not_delete flag to release.json format

---

docs/_static/css/custom.css
docs/_templates/layout.html

Turned out that we can't just use `display: flex` on the `<dialog />`, otherwise it conflicts with `display: none;` and thus showing the dialog when it's supposed to be hidden!
https://github.com/chanzuckerberg/cellxgene-census/assets/6309723/7581d2a5-0819-43dc-8c55-1bfa8a321749

fix: dialog

---

docs/_static/css/custom.css
docs/_templates/layout.html

1. Add LocalStorage to store dismissed state for 30 days
2. WARNING: Since the Census doesn't share the same domain as the main site, dismissing the banner on the main site won't dismiss it on the Census doc page. And vice versa
https://github.com/chanzuckerberg/cellxgene-census/assets/6309723/a9cce4d2-43b0-45d7-a7a3-c02cb6a3a4d1

feat(newsletterBanner): Add localStorage

---

.github/workflows/py-build.yml

Use the correct role when pushing the Docker image for the builder. Currently, the builder is pushed to the dev account, which resulted in the builder pipeline not running the latest code.
(Note: in the future, we could push this to both dev and prod, but for the time being we aren't really doing dev testing, so I figured it wasn't worth it).

Switch to prod role for the builder GHA job

---

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_state.py

Update to the host validation check for minimum disk space.  As of PR #612, the disk space usage is roughly 1.8TiB.

bump Census build minimum disk space requirement to 1.8TiB

---

api/r/cellxgene.census/DESCRIPTION
api/r/cellxgene.census/R/get_helpers.R
api/r/cellxgene.census/README.md
docs/cellxgene_census_docsite_installation.md

- Changes Seurat and SingleCellExperiment from depends to suggest. 
- Updates install instructions

Change R Dependencies

---

api/r/cellxgene.census/vignettes_/comp_bio_data_integration.Rmd

Three minor changes, feel free to skip or ignore any or all
- R usually talks about 'packages' rather than 'modules'
- patchwork is imported by Seurat so we can skip library(Seurat)
- the initial Seurat data load step calls it AnnData

Suggesting very minor edits to comp_bio_data_integration.Rmd

---

.pre-commit-config.yaml
api/python/cellxgene_census/src/cellxgene_census/experimental/pp/_stats.py
api/python/cellxgene_census/src/cellxgene_census/experimental/util/_csr_iter.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/validate_soma.py
tools/cellxgene_census_builder/tests/anndata/test_anndata.py
tools/cellxgene_census_builder/tests/test_manifest.py
tools/cellxgene_census_builder/tests/test_release_manifest.py

Fixes #599 
Builder code logs ERROR messages in some cases, which pytest dutifully records.  There does not appear to be a way of suppressing the reporting of specific, expected, log messages, so I have added explicit tests for them, to acknowledge that we expect them.
Also resolved: 
* updated mypy to latest version
* remove a few typing hints which are no longer necessary
Note to reviewer (CC @ebezzi) - due to changes to the live release.json, motivated by #552, the Builder unit tests are broken.  I have added xfails where needed, and @ebezzi will resolve these issues in his PR.

Explicit log message tests

---

docs/conf.py

Tentatively fixes #711 
I am not sure why the `tag` object is sometimes None, but this should fix it. The issue isn't easily reproducible since tags are global and the current state of the git repo doesn't present this issue.

[docs] add explicit filtering for None git tags

---

docs/requirements.txt

Sphinx 7 doesn't work with the theme we're using (readthedocs). Pinning Sphinx for now.

[docs] pin Sphinx version

---

api/python/cellxgene_census/pyproject.toml
api/python/cellxgene_census/src/cellxgene_census/_open.py

Fixed #415 
Tested on M1 via installation of a locally built wheel.

revert Mac M1/M2 cert fix on open_soma()

---

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/globals.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/util.py

This PR adds configuration for thread usage, focused on lowering the number of unused threads on very high CPU count boxes.  Changes:
* set environment variables which configure load-time thread pool allocation for imported sub-modules. Example:  OpenMP
* cap TileDB and NumExpr thread pools to a useful number
Fixes #755 
Related to single-cell-data/TileDB-SOMA#1550
Note to reviewers: I have run a full build and there is no observed performance degradation.

[builder] thread usage tuning

---

tools/cellxgene_census_builder/entrypoint.sh
tools/cellxgene_census_builder/src/cellxgene_census_builder/__main__.py

Add additional builder logging, namely: 
1. Output of `pip freeze`
2. TileDB configuration used
3. If the builder fails, output of `df` to check the disk space situation

[builder] Add additional debug logging

---

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/consolidate.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/globals.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/validate_soma.py

Fixes #772 
Consolidation has multiple modes, for each type of object and metadata.  This PR adds consolidation/vacuuming of all modes. This does not add any substantial time to the build, as we were already doing the expensive consolidation steps.
Note: there is a bug in TileDB-Py that prevents the consolidation/vacuuming of group metadata. Reported and awaiting fix.  Disabling this step until such time as it is resolved - with work item captured in #776.

[builder] perform all consolidation modes

---

api/python/cellxgene_census/tests/experimental/pp/test_hvg.py
api/python/cellxgene_census/tests/experimental/pp/test_stats.py
api/python/cellxgene_census/tests/test_acceptance.py

We have several `--expensive` unit tests, used for acceptance testing upstream packages such as tiledbsoma.  As the Census has grown, their run-times have gotten out of control.  
This PR adds caps on the max size of the queries performed by a handful of the tests, to keep their run time reasonable.  The primary mechanism is to add an obs coordinate range to queries, restricting them to some maximum number of results.

[python] limit runtime of --expensive unit tests

---

api/python/cellxgene_census/src/cellxgene_census/experimental/ml/huggingface/geneformer_tokenizer.py

1. Disable the `var_query` for now since we have seen it actually slow things down. Still investigating why. Without it, we get the full expression vector for all genes, and select the ones of interest.
2. Refactor some of the tokenizer computations, equivalent but faster.

[python] GeneformerTokenizer speed optimizations

---

.github/workflows/lts-compat-check.yml
README.md
api/python/cellxgene_census/pyproject.toml
api/python/cellxgene_census/tests/conftest.py
api/python/cellxgene_census/tests/test_lts_compat.py

Add a GHA that checks for compatibility between a matrix of:
* cellxgene_census package versions
* Census LTS versions
Intended to be run nightly as a canary for any incompatibility between past LTS releases and evolving access packages.
Note: down the road, if the matrix size gets out of control, we can always consolidate along the Census build axis and just have a loop that runs over all Census build versions in a single GHA.
FYI: @mlin - it may be worth considering adding something similar for the R package, although there are diminishing returns as both language bindings share a large common implementation base.

LTS / package compatibility check

---

tools/cellxgene_census_builder/pyproject.toml

Fixes #799 
Update builder to use TileDB core 2.16.
Also updates other miscellaneous dependency pins to more recent versions, where there are no conflicts upstream.

[builder] use TileDB core 2.16

---

api/python/cellxgene_census/pyproject.toml

In preparation for working on #801 and upgrading to the soon-to-arrive tiledbsoma 1.5, this cleans up unnecessary pins in our Python package dependencies. The SciPy pin was due to an old incompatibility with Arrow, now resolved.

[python] remove unnecessary dependency pin

---

.github/workflows/lts-compat-check.yml

The full GHA name is displayed in the badge, which is shown on the top of the README.
Shorten to make the README a bit less verbose.

[misc] shorten Census LTS compatibility workflow name

---

tools/cellxgene_census_builder/pyproject.toml

Fixes #811 
Update the tiledbsoma pin to 1.4.4 to benefit from concurrency bug fix in that release.

[builder] update tiledbsoma pin to 1.4.4

---

api/python/cellxgene_census/tests/experimental/ml/huggingface/test_geneformer.py

Due to my neglecting to ask for do_not_delete to be set on a certain Census version the GeneformerTokenizer unit tests were coded against, it has now been deleted. The tests cannot use the current stable version because it doesn't have the normalized X layer. The tests also do not work against latest as the soma_joinids have changed.
I will need to overhaul this but it will probably take me a few days to get to, so marking the tests to skip in the meantime. Apologies all. (The overhaul may be an opportunity to switch to a token sequence checksumming approach suggested by Theodoris lab)

[python] temporarily skip geneformer tests

---

api/python/cellxgene_census/pyproject.toml
api/python/cellxgene_census/src/cellxgene_census/py.typed

Fixes #806 
Add marker file indicating use of line typing for the cellxgene_census package.

[python] add PEP 561 py.typed marker

---

api/python/cellxgene_census/src/cellxgene_census/experimental/pp/_highly_variable_genes.py
api/python/cellxgene_census/src/cellxgene_census/experimental/pp/_online.py
api/python/cellxgene_census/tests/experimental/pp/test_hvg.py

Fixes #817 
loess.fit will crash with empty array input. Changes:
* correctly handle cases where batch key over-segments, resulting in batch sizes of zero or one
* fix several numerical precision/correctness issues found while debugging
* improve HVG unit tests, and allow for inevitable precision noise in "expensive" tests
* remove some expensive HVG unit tests from our standard CI (move to "expensive")

[python] Fix HVG crasher

---

.github/workflows/py-dependency-check.yml
api/python/cellxgene_census/scripts/requirements-dev.txt

RE: #831 
Ports a workaround for installing a gnarly transitive dependency of Geneformer, [from py-unittests.yml](https://github.com/chanzuckerberg/cellxgene-census/blob/1d071d6e189a32c3a040e67a43e981ba7f082701/.github/workflows/py-unittests.yml#L28-L29) to py-dependency-check.yml.
Due to this dependency that's difficult on certain platforms (cython etc.), we leave Geneformer out of the pyproject.toml dependencies and instead raise [a runtime error](https://github.com/chanzuckerberg/cellxgene-census/blob/1d071d6e189a32c3a040e67a43e981ba7f082701/api/python/cellxgene_census/src/cellxgene_census/experimental/ml/huggingface/geneformer_tokenizer.py#L104-L111) asking end users to install it when needed. However, we do need to install it in GHA in order to run the unit tests (which albeit are …

fix installation of geneformer's transitive dependency in py-dependency-check.yml

---

tools/cellxgene_census_builder/src/cellxgene_census_builder/__main__.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_state.py
tools/cellxgene_census_builder/tests/test_workflow_steps.py

Mirror resolution is done via the `mirrors.json` file on newer versions of the census API, but for legacy reasons we're still supporting absolute URIs. These don't support mirrors and should just point to the default one.
Also note that the h5ad functions also do not support mirroring, and still read from the absolute uris. This was done on purpose due to the original intent of deprecating those h5ads locations, but we should probably update them now. I can submit a separate PR for it.

[builder] Absolute uris should use the default mirror

---

api/python/cellxgene_census/tests/test_open.py
api/r/cellxgene.census/tests/testthat/helper-open_soma.R
api/r/cellxgene.census/tests/testthat/test-open.R
tools/cellxgene_census_builder/tests/test_release_manifest.py

Some tests had the `cellxgene-data-public` mirror hardcoded and stopped working after the migration.

Fix tests that had the mirror name hardcoded

---

tools/cellxgene_census_builder/src/cellxgene_census_builder/release_manifest.py

Fixes an issue introduced by the switch to the new bucket in the `uri` field. To keep the code simple, I removed the explicit `uri` check in the manifest validation - I think this is acceptable since that is now a legacy field. Alternatively, we can pass the "default mirror bucket" all the way to that function, but that will make the code more complex. @bkmartinjr let me know what you think.

[builder] Fix builder release manifest validation to not check for absolute uri

---

api/python/cellxgene_census/pyproject.toml
api/python/cellxgene_census/src/cellxgene_census/_get_anndata.py
api/python/cellxgene_census/tests/test_get_anndata.py

Resolves #874 
Note: currently there are no unit tests that do not rely on the live corpus for data layers. Since `obsm` isn't yet available in any live Census distributions, the unit tests are marked as skipped.

[python] upgrade to tiledbsoma and add obsm to get_anndata

---

tools/cellxgene_census_builder/src/cellxgene_census_builder/release_cleanup.py

These assert do not work anymore because the absolute uri doesn't match the uri of the primary bucket anymore. I don't believe other assertions are necessary here. We could force a check that the URI matches a hardcoded pattern if we want to keep a defensive assert, but it will break again if we (e.g.) decide to change the location of the primary bucket.

[builder] Update release cleanup code to support relative URIs

---

tools/models/geneformer/Dockerfile
tools/models/geneformer/README.md
tools/models/geneformer/generate-geneformer-embeddings.py
tools/models/geneformer/wdl/generate_embeddings.wdl
tools/models/geneformer/wdl/prepare_datasets.wdl

Pin the TileDB and Census versions to ensure compatibility with embeddings curator

[python] Geneformer WDL: pin TileDB and Census versions

---

api/python/cellxgene_census/tests/test_open.py

- reinstate `vfs.s3.no_sign_request=True` setting to allow these tests to pass on EC2 instances that have an IAM role and that does not grant explicit access to the bucket
- remove one test, `test_open_soma_with_plain_soma_context()` that can never be successfully run under these circumstances; there is still sufficient coverage from other tests
- tweak test assertions
Tests passing on GHA standard runner and on EC2 instance with IAM role, where tests previously failed.  Relevant tests pass on GHA custom runner: test run [here](https://github.com/chanzuckerberg/cellxgene-census/actions/runs/7266987244)

fix tests with invalid vfs.s3.no_sign_request setting

---

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/validate_soma.py

The builder has checks for a latent tiledbsoma bug, which were too aggressive.  Change from assert to warn in cases of known failure.

[builder] fix overzealous assertion in builder

---

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/build_soma.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/validate_soma.py

Fixes #912 
Remove the bounding box metadata from all SparseNDArray objects in the Census, as a work-around for single-cell-data/TileDB-SOMA#1969

[builder] delete bounding box metadata on sparse arrays

---

docs/cellxgene_census_schema.md

This updates the census schema markdown file to point at the 4.0.0 CxG schema (a change missed during the upgrade to 4.0.0)

[misc] census schema: update CxG schema ref to 4.0.0

---

api/python/cellxgene_census/src/cellxgene_census/experimental/_embedding.py
api/python/cellxgene_census/tests/experimental/ml/huggingface/test_geneformer.py

Unit tests and some docstrings had an obsolete Census version, the former which caused our GHA unit tests to fail.  Updating to use the most recent LTS version.

[misc] update census test version to use 2023-12-15 LTS version

---

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/source_assets.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_state.py

Changes:
* Added two configuration variables for the Builder User-Agent HTTP header:
*  `user_agent_prefix` -- defaults to "census-builder-"
* `user_agent_environment` - defaults to "unknown"
* Set the User-Agent HTTP header on all H5AD requests to https://datasets.cellxgene.cziscience.com/...   The user agent value will be:    `prefix-environment/version`.  For example:   `census-builder-unknown/1.9.2.dev14+gb43f4bf`
Partial solution for #928
Note to reviewers: this was manually verified as working.  Building a unit test for this is a PITA, so I biased towards landing the functionality sooner....
Remaining work: in production, setting the environment variable `CENSUS_BUILD_USER_AGENT_ENVIRONMENT="prod"` (or whatever value we want it to be).

[builder] add user agent HTTP header to H5AD requests

---

.github/workflows/py-dependency-check.yml

Self-hosted runners do not have the same tooling as GH hosted.  Install missing items
Important note to reviewers:  this weekly GHA will continue to fail until we ship a new release of the Census package, for two reasons:
* there was a bug in the tests at the time of the release
* the tests at the time of the release specified a (now) non-existent census version as a test dataset
Both of these will resolve when we do the next release.
This PR fixes a separate issue - the lack of certain tooling on the self-hosted Linux runners.

[misc] fix python dependency check workflow

---

api/python/cellxgene_census/src/cellxgene_census/experimental/diffexp/memento/diff_expr.py
api/python/cellxgene_census/tests/experimental/diffexp/memento/test_diff_expr.py
tools/models/memento/src/estimators_cube_builder/cube_builder.py
tools/models/memento/src/estimators_cube_builder/cube_schema.py
tools/models/memento/src/estimators_cube_builder/estimators.py
tools/models/memento/src/estimators_cube_builder/migrate_schema.py

- Updated the cube builder to store the sum, sumsq, n_obs, and size_factors
- Updated the diff_expr module to calculate mean and sem on the fly, performing the necessary aggregations along the user-selected covariates.
- Removed `n_features`. All features will be selected.
The script was run with the following params:
`"tissue_general_ontology_term_id in ['UBERON:0002048'] and cell_type_ontology_term_id in ['CL:0000786', 'CL:0000187']" cell_type_ontology_term_id ~/czi/cellxgene-census/memento-cube-2024-01-29 1 dataset_id,assay_ontology_term_id`
The results were quickly sanity checked.

feat: allow users to select covariates for memento

---

.github/workflows/docsite-build-deploy.yml
.github/workflows/lts-compat-check.yml
.github/workflows/py-dependency-check.yml
.github/workflows/py-formatting.yml

This PR resolves the warnings about using an obsolete version of setup-python (node16 deprecation) in various GHA workflows.

[misc] update to setup-python v5

---

docs/python-api.rst

Let me know if this is a welcome change! Adds the model embedding API to the docs (`get_embedding` and `get_embedding_metadata`).

[docs] Add embeddings API to docs

---

tools/cellxgene_census_builder/entrypoint.sh

The builder lacked thread allocation config for the main thread, resulting in unused/excessive thread allocation in the main thread.  This is a companion to `env_var_init()`, which sets the config for all child (worker) processes.

[builder] thread usage config for main thread

---

docs/cellxgene_census_schema.md
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/anndata.py
tools/cellxgene_census_builder/tests/anndata/conftest.py
tools/cellxgene_census_builder/tests/conftest.py

Fixes #1009 
In the update to handle schema 4, the obs axis filtering for organoid and cell culture was not implemented.  This PR resolves that.
Changes:
* Obs filter on `tissue_type == "tissue"`
* Fix tests to match
* update schema doc to match

[builder] fix incorrect filtering of tissue type

---

.github/workflows/py-build.yml

Fixes #985 
Until our GH runners have docker buildx installed, do so manually.

[misc] use docker buildx

---

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/validate_soma.py

Additional check related to #1009 - explicitly check that all cells in the census SOMA object are `tissue_type=="tissue"`

[builder] add explicit validation check for primary tissue cells

---

.github/workflows/profiler.yml
tools/perf_checker/perf_checker.py
tools/perf_checker/perf_checker.sh
tools/perf_checker/test_anndata_export.py

Include a basic benchmark as the starting point and needed scripts

Early version of profiler harness

---

tools/models/geneformer/finetune-geneformer.config.yml

Fixes #1019
Schema 5.0 will use an updated ontology that does not include `CL:0000003 - native cell`. We will accept instead `"unknown"` for the `cell_type_ontology_term_id`, and accordingly we will annotate `cell_type` (label) as `"unknown"`.
This should (probably) be merged once we migrate. @mlin let me know if you foresee any issues.

feat: 'native cell' -> 'unknown' on geneformer label_blocklist -- DO NOT MERGE (yet)

---

.github/workflows/r-check.yml

The build will now automatically pull TileDB-R 1.9.0, so we don't need this workaround anymore.

[R] fix R CI

---

api/python/cellxgene_census/src/cellxgene_census/experimental/pp/_highly_variable_genes.py
api/python/cellxgene_census/tests/experimental/pp/test_hvg.py

Due to [this change](https://github.com/scverse/scanpy/commit/82f84129ed895dfdded3111b98aa4dc2ae5d4887#diff-a3319950a357c8d24de0f78d7e64852aa3c8a5b59d3a633e960d088c86528f53R137) in Scanpy's implementation, there is now a new `gene_name` field that gets added to the returned dataframe. This PR adds the same field to our implementation.

[python] fix hvg_vs_scanpy test

---

api/python/cellxgene_census/pyproject.toml
api/python/cellxgene_census/src/cellxgene_census/experimental/_embedding.py
api/python/cellxgene_census/src/cellxgene_census/experimental/pp/_highly_variable_genes.py
api/r/cellxgene.census/DESCRIPTION

This release of the census package is being done to include an important update for `tiledbsoma` in `1.9.0` which includes a fix to categorical columns. To ensure that this release goes smoothly, we will:
1. Run an acceptance test off `TileDB-SOMA` `main` [branch](https://github.com/single-cell-data/TileDB-SOMA/tree/main) which contains the fixes that will go into `1.9.0`. We can think of this as a _pre-release acceptance test_
2. After (1) passes and the tiledb folks officially release `tiledbsoma==1.9.0`, we will update the dependencies in this PR to point to `tiledbsoma==1.9.0` and do the official release of `cellxgene-census==1.12.0`

[misc] Prepare for 1.12.0 release

---

.github/workflows/lts-compat-check.yml
.github/workflows/py-dependency-check.yml
.github/workflows/r-dependency-check.yml

The weekly checks that explore the full matrix of version/census build/etc. had GHA fast-fail enabled.  For these periodic checks, it is better to not fast-fail, and see which pats of the test matrix work and which are in error.  They are not run during the normal dev cycle, so there is little downside, and this will help diagnose actual issues faster.

[misc] turn off fast-fail for weekly CI checks

---

api/python/cellxgene_census/src/cellxgene_census/experimental/pp/_highly_variable_genes.py

HVG unit test was failing due to assumption that label columns would be non-categorical, which is no longer true. Generalized test so it works with both series type.

[python] fix HVG unit test

---

.pre-commit-config.yaml
api/python/cellxgene_census/src/cellxgene_census/_get_anndata.py
api/python/cellxgene_census/src/cellxgene_census/_open.py
api/python/cellxgene_census/src/cellxgene_census/_release_directory.py
api/python/cellxgene_census/src/cellxgene_census/experimental/_embedding.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/__main__.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/anndata.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/build_soma.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/consolidate.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/util.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_state.py
tools/cellxgene_census_builder/tests/test_builder.py
tools/cellxgene_census_builder/tests/test_main.py
tools/census_contrib/src/census_contrib/load.py

Changes:
* dead code removal - items missed in Dask refactor
* autoupdate and run pre-commit - minor reformatting from this
* in tests for `build()`, mock psutil.virtual_memory to reduce apparent host memory. This is to reduce occurrences of OOM in small test runners (which lack swap)

[builder] cleanup chore

---

tools/cellxgene_census_builder/tests/anndata/conftest.py
tools/cellxgene_census_builder/tests/anndata/test_anndata.py
tools/cellxgene_census_builder/tests/conftest.py
tools/cellxgene_census_builder/tests/test_builder.py
tools/cellxgene_census_builder/tests/test_data_copy.py

Changes:
* More coverage of `build()` tests, including all supported X array formats
* add explicit test of the data copy (to s3) functions

[builder] additional unit tests for builder

---

tools/cellxgene_census_builder/pyproject.toml
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/experiment_builder.py

- Remove MacOS support claim for census builder
- Fix type annotation of the dask computation that returns a list of `obs` and `var` dataframe as tuples

[misc] Remove MacOS support claim for census builder

---

tools/cellxgene_census_builder/pyproject.toml
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/globals.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/tissue_mapper.py
tools/cellxgene_census_builder/tests/test_tissue_mapper.py

Integrate cellxgene_ontology_guide in place of the old TissueMapper.

[builder] cellxgene_ontology_guide integration

---

.github/workflows/py-unittests.yml
api/python/cellxgene_census/pyproject.toml

1. Pins torch to 2.2.x, as 2.3.x is causing dependency issues (these will eventually be fixed, so we should periodically retry unpinning the dependency)
2. Pause python 3.8 tests on the MacOS runner, at least temporarily. This is an issue with `gfortran` - maybe something like https://github.com/actions/runner-images/issues/3371 could help with solving the issue.

[ci] Fix torch dependency issue and pause tests on Mac/Python3.8

---

api/python/cellxgene_census/tests/experimental/ml/test_pytorch.py

Some of the imports in test_pytorch.py were causing the tests to fail even if they were not invoked (as in, not in experimental mode). This should fix the issue.

[python] Fix pytorch imports

---

.github/workflows/r-check.yml
.github/workflows/r-dependency-check.yml

Removes the requirement to install from source. This is not required on Mac and it only causes unnecessary headaches.

[R] Fix R dependency workflow

---

.github/workflows/py-dependency-check.yml

Required (at least for now) due to an issue with Python 3.8 on the MacOS runners.

Add python 3.8/MacOS exclusion rule for dependency check workflow

---

api/r/cellxgene.census/DESCRIPTION
api/r/cellxgene.census/tests/testthat/acceptance-tests.R
api/r/cellxgene.census/tests/testthat/helper-acceptance.R

Forces garbage collection after each iteration in the test helper iterative function. This has been proven to work empirically.

[R] Fix acceptance tests memory issue

---

api/python/cellxgene_census/README.md

This is one of a series of PRs to improve developer documentation for the Census repository as stated in #1109

[docs] Add development setup notes for Census API

---

.github/workflows/py-unittests.yml

Attemps to fix an issue caused by git-lfs which is used by Geneformer tests.

[python] Fix git-lfs issue when cloning Geneformer

---

api/python/cellxgene_census/src/cellxgene_census/__init__.py
api/python/cellxgene_census/src/cellxgene_census/_get_anndata.py
api/python/cellxgene_census/tests/test_get_anndata.py
docs/python-api.rst

Fixes https://github.com/chanzuckerberg/cellxgene-census/issues/1037

[python] Add get_obs

---

.github/workflows/py-unittests.yml
api/python/cellxgene_census/tests/test_ci.py

It's working! You can see that on commit fafb3ff the actions all quit after one failure, but after b2058a0 they continue to run. 
~~I'm starting this with a test that should fail on some jobs, to confirm that it kills the others. Then I will modify the workflow file to make it so that doesn't happen.~~

[python] Don't kill all tests on failure

---

api/python/cellxgene_census/tests/conftest.py
api/python/cellxgene_census/tests/test_get_anndata.py
api/python/cellxgene_census/tests/test_get_helpers.py

I propose we re-use SOMA objects in testing to cut down on total test time.
From a single measurement, I see a little more than a 10% (~40 seconds) decrease in test time with this change. I've run the `get_anndata` tests on this commit and the one before it. I haven't run this many times, so I don't know what the variance is. You can see that with this commit there is far lower time taken on setup for each task (since the resource is simply removed)
<details>
```
================================================================================ slowest durations ================================================================================
53.89s call     tests/test_get_anndata.py::test_get_anndata_allows_missing_obs_or_var_filter
34.26s call …
```

[python] share census objects in tests for faster test time

---

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/source_assets.py

I'm assuming that the original idea is that `ClientResponseError` should be escalated since it's not a transient error (e.g. 404), but the recent failures suggest otherwise.

[builder] Add ClientResponseError to the builder managed exceptions

---

docs/conf.py

This PR addresses https://github.com/chanzuckerberg/cellxgene-census/issues/620
I've re-enabled Sphinx's built-in client side search by:
* Removing the blank template for the search bar
* Removing the line:
```python
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
```

[python] Make docs searchable

---

api/python/cellxgene_census/src/cellxgene_census/_open.py
api/python/cellxgene_census/tests/test_open.py

For #1033
Adding a progress bar for download_source_h5ad
TODO:
- I does a text based progress bar in a vscode notebook. There is an HTML one, but the main difference is that the html one is blue.
Currently looks like:
```python
In [3]: cellxgene_census.download_source_h5ad(small_dataset.dataset_id, "tmp.h5ad")
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 5.10M/5.10M [00:00<00:00, 17.7MB/s]
```

[python] Progress bar for download_source_h5ad

---

.github/workflows/docsite-build-deploy.yml
.readthedocs.yaml
api/python/cellxgene_census/pyproject.toml
dev-docs/README.md
docs/requirements.txt

This PR moves the doc requirements over to the pyproject.toml for an easier install workflow.

[python] Use pyproject.toml for doc env

---

api/python/cellxgene_census/src/cellxgene_census/experimental/ml/pytorch.py

Not sure how those ended up there in the first place.

[python] Fix wrong parameters in ExperimentDataPipe

---

api/python/cellxgene_census/src/cellxgene_census/experimental/pp/_highly_variable_genes.py

Previously removed due a memory bug, now fixed by https://github.com/single-cell-data/TileDB-SOMA/issues/2662

[python] Restore soma indexer in hvg

---

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/experiment_builder.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/validate_soma.py
tools/census_contrib/src/census_contrib/__main__.py
tools/perf_checker/perf_checker.py

There were calls to `logging.info` or `logging.debug`. They should be `logger.info` and `logger.debug`.

Fix incorrect logger calls

---

api/python/cellxgene_census/pyproject.toml

While developing, local tiledbsoma installs get version numbers like `1.11.4.post0.dev3991933300`. The `tiledbsoma==1.11.4` pin in this repo errors when attempting to install alongside such a tiledbsoma, e.g. [in arrayloader-benchmarks](https://github.com/ryan-williams/arrayloader-benchmarks?tab=readme-ov-file#install):
```bash
pip install -e cellxgene-census/api/python/cellxgene_census -e tiledb-soma/apis/python
```
`tiledbsoma~=1.11.4` (equivalent to `tiledbsoma>=1.11.4,<1.12.0`) lets such local installs work, and doesn't have any downsides, afaict.
(factored out of #1169)

[python] Relax pin: `tiledbsoma~=1.11.4`

---

api/python/cellxgene_census/src/cellxgene_census/experimental/ml/pytorch.py
api/python/cellxgene_census/tests/experimental/ml/test_pytorch.py

1. Set shuffle=True as the default for ExperimentDataPipe
2. Use the new scatter-gather algorithm by default
3. Set the soma_chunk_size, shuffle_chunk_count to a sensible default of (64, 2000)
4. Modify docs to explain the above changes
5. Set shuffle=False in the tests (to avoid nondeterminism)

[pytorch] Set shuffle as default in pytorch, use new algorithm

---

api/python/cellxgene_census/pyproject.toml

Pin no longer required with the 2.3.1 release:
https://github.com/pytorch/pytorch/pull/122616

[python] Remove pytorch pin

---

tools/census_embeddings_indexer/Dockerfile
tools/census_embeddings_indexer/README.md
tools/census_embeddings_indexer/census_embeddings_indexer.wdl

#1112 
Adds a Docker+WDL pipeline to build the [TileDB-Vector-Search](https://github.com/TileDB-Inc/TileDB-Vector-Search) index for each Census embedding. (Excluding NMF for now due to some minor technical issues that will be easier to deal with after future improvements to TileDB-Vector-Search.)
The pipeline launches a powerful instance to build the index for each embedding, and processes the embeddings in parallel. The longest takes 9-10 hours to build (UCE, which has the highest dimensionality). The output is an S3 folder which can be copied into the destination bucket.

Vector indexing pipeline for Census embeddings

---

api/python/cellxgene_census/src/cellxgene_census/experimental/_embedding.py

This fixes a mypy error that arose spontaneously, probably due to a change in mypy or numpy. Seen in this CI run for my completely unrelated commit on main: https://github.com/chanzuckerberg/cellxgene-census/actions/runs/9558859502/job/26348249505#step:5:145
That commit is completely unrelated but fortunately I hit this problem while separately working on #1164 where I also put this fix.

[python] fix mypy complaint in experimental/_embedding.py

---

api/python/notebooks/api_demo/census_access_maintained_embeddings.ipynb

Fixes #1206
I've re-run the notebook locally, so don't think I've introduced a new error

[python] Fix typo in embedding notebook

---

api/python/cellxgene_census/pyproject.toml

Scikit-misc 0.4 doesn't have compatible wheels for MacOS/ARM: see https://github.com/has2k1/scikit-misc/issues/37

[python] Require scikit-misc < 0.4

---

api/python/cellxgene_census/src/cellxgene_census/_release_directory.py
api/python/cellxgene_census/tests/test_directory.py

[python] Stop including `"do_not_delete"` key in result of `get_census_version_directory`

---

api/python/cellxgene_census/src/cellxgene_census/experimental/ml/pytorch.py
api/python/cellxgene_census/tests/experimental/ml/test_pytorch.py

[python] Fix ExperimentDataPipe length

---

api/python/cellxgene_census/tests/conftest.py
api/python/cellxgene_census/tests/experimental/test_embeddings.py
api/python/cellxgene_census/tests/test_get_anndata.py

Tests were adapted to account for temporary lack of embeddings in the new LTS. Now that they have been published, tests can be reintroduced.

[python] Reintroduce embeddings tests

---

.github/workflows/py-unittests.yml
api/python/cellxgene_census/scripts/requirements-dev.txt

This makes the dep available for all CI runs, and makes it available locally for running tests.
cc: @ebezzi @mlin

Move geneformer test dependency back to requirements-dev.txt

---

api/python/cellxgene_census/tests/experimental/pp/test_hvg.py

https://github.com/chanzuckerberg/cellxgene-census/actions/runs/9882376259/job/27295103088
The test failure on the full tests is due to the new LTS.  The test uses both `value_filter` and `coords` on stable, but now that ends selecting 0 cells. I think we should probably just pin this test to a specific LTS release.
```python
census["census_data"]["mus_musculus"].axis_query(
measurement_name="RNA",
obs_query=tiledbsoma.AxisQuery(value_filter="is_primary_data == True", coords=(slice(750_000, 1_000_000),)),
).to_anndata(X_name="raw").shape
```
Starting another test run on this branch: https://github.com/chanzuckerberg/cellxgene-census/actions/runs/9899971112

Pin census release version used in test

---

api/python/cellxgene_census/pyproject.toml
api/python/cellxgene_census/src/cellxgene_census/experimental/ml/pytorch.py
api/python/cellxgene_census/tests/test_open.py
tools/cellxgene_census_builder/tests/test_builder.py
tools/models/geneformer/generate-geneformer-embeddings.py
tools/models/geneformer/wdl/generate_embeddings.wdl

Bump `tiledbsoma` dep to 1.12.3.
I believe the remaining deprecations being thrown are actually coming from `tiledbsoma`, since this PR removes all use of `tiledb_ctx`.

[python] Bump tiledbsoma version to 1.12.3

---

api/python/cellxgene_census/scripts/requirements-dev.txt

`owlready2` is causing CI failures for python 3.8 and 3.9 since there's no wheel, and building from source fails.
It also looks like it's not actually necessary for the API tests (from local running), so I've just removed it here.

[python] Remove owlready2 dev dep

---

docs/cellxgene_census_docsite_FAQ.md

This looks like:
Towards https://github.com/chanzuckerberg/cellxgene-census/issues/1265
@pablo-gar, why is there a manual table of contents on top in the FAQ section when there already an equivalent table of contents in the sidebar?

Add FAQ on access from behind a proxy

---

api/python/cellxgene_census/src/cellxgene_census/experimental/_embedding_search.py
api/python/cellxgene_census/tests/experimental/test_embeddings_search.py

As reported by @MaximilianLombardo, prior to this PR `predict_obs_metadata` breaks if `find_nearest_obs` receives anything except 10 for the number of nearest neighbors. This value was unintentionally hardcoded.
This PR adds a simple test which makes sure the neighbors param is being respected by `find_nearest_obs` and that `predict_obs_metadata` doesn't error when given the result of that operation. The test could be improved by checking the correctness of the results.

[python] Fix `predict_obs_metadata` when number of neighbors isn't `10`

---

api/python/cellxgene_census/src/cellxgene_census/experimental/_embedding_search.py

Fixes https://github.com/chanzuckerberg/cellxgene-census/issues/1283

[python] Fix vector search import

---

docs/_templates/layout.html

Added back bottom banner and newsletter signup
Based on this reverted [PR](https://github.com/chanzuckerberg/cellxgene-census/pull/1161/files)

chore(docs): Add banner and newsletter signup (SCE-29)

---

api/python/cellxgene_census/src/cellxgene_census/experimental/ml/pytorch.py

Fixes #1291
A couple places in the docs still said we include the join id by default. I think this catches all the remaining places.

[Python] Correct docs on default behaviour for DataLoader no longer including soma_joinid

---

api/python/cellxgene_census/tests/experimental/ml/test_pytorch.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/census_summary.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/datasets.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/experiment_builder.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/summary_cell_counts.py
tools/cellxgene_census_builder/tests/test_builder.py

I'm making this change to make our builder compatible with the next release of tiledbsoma. I don't believe there should be any changes needed on the client side, and believe this should work for current releases cellxgene_census.

Add domain handling to dataframe write code

---

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/manifest.py
tools/cellxgene_census_builder/tests/test_manifest.py

For some reason changing the size of our manifest file has broken our code to read it. It has something to do with how the file is encoded. I believe it is related to https://github.com/fsspec/filesystem_spec/issues/389.
The issue only comes up due to some handling of partial reads. So I switched to doing a full read since the file is never that large.
We use fsspec instead of requests since sometimes we read a local file or one from s3.

Fix reading manifest file when it's only one line and also served by GitHub

---

api/python/cellxgene_census/pyproject.toml
api/python/cellxgene_census/src/cellxgene_census/experimental/ml/huggingface/cell_dataset_builder.py
api/python/cellxgene_census/src/cellxgene_census/experimental/pp/_online.py
api/python/cellxgene_census/tests/experimental/pp/test_online.py
api/python/cellxgene_census/tests/test_get_helpers.py
tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/validate_soma.py
tools/census_contrib/src/census_contrib/load.py

This has ended up being a bit of a grab bag targeting some CI issues that have come up over the past couple weeks.
* Pin torchdata to a version that has datapipes
* Fix a number of mypy issues, mostly having to do with numpy typing thinking that operations might change the floating point type. A few of these are around us changing re-assigning a variable with a reshaped version.
* Fix a test that was prematurely closing a tiledbsoma object, which was then re-used in later tests. This probably should have been failing before, so something must have been fixed in tiledbsoma.

Pin torchdata + fix some typing errors

---

.github/workflows/lts-compat-check.yml

LTS compatibility tests have been failing for the past four months. I believe this is mostly due to uninstallable dependencies for old very old versions of the package.
Checking here: https://github.com/chanzuckerberg/cellxgene-census/actions/runs/12661005585
Run with:
```
gh workflow run lts-compat-check.yml --ref ivirshup/fix-lts-compat-tests
```

Fix LTS compat tests

---

tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/validate_soma.py

This is required because now there can be experiments with the same name but belong to two different types (rna-seq, spatial)

fix validation experiment key

---

docs/articles/2025/20250117-spatial.md
docs/conf.py

* Added links to relevant `tiledbsoma` and `spatialdata` doc pages
* Fixed outdated image documentation
This looks like:
Where the bolded code titles link to the tiledbsoma documentation.
* `.levels()` is not currently documented, but was on the original set of attributes to document. I will check in with tiledb on this

Touch up of spatial release article

---

.github/workflows/py-build.yml
.github/workflows/py-unittests.yml

https://czi.atlassian.net/browse/CCIE-3911
This PR updates 'runs-on' in GitHub Actions workflow files to use direct values instead of label arrays.

fix: Update runs-on labels in GitHub Actions workflows

---

.github/workflows/r-dependency-check.yml

tiledbsoma [now requires GCC/G++13](https://github.com/single-cell-data/TileDB-SOMA/releases/tag/1.16.0).

[r] dependency check CI: make GCC 13 available

---

.github/workflows/docsite-build-deploy.yml
.github/workflows/full-unittests.yml
.github/workflows/profiler.yml
.github/workflows/py-build.yml
.github/workflows/py-dependency-check.yml
.github/workflows/py-unittests.yml
api/python/cellxgene_census/scripts/requirements-dev.txt
api/python/cellxgene_census/tests/experimental/ml/huggingface/test_geneformer.py

This PR uses CZI managed runners for most tests, then a GitHub hosted one for census since the flaky test always fails on CZI managed ones
This PR:
* Moves most workflows to run on CZI managed runners
* Census builder tests not moved, since a flaky test seems to always fail on these
* Moves the census builder tests to run on GitHub managed runners
* Pins a geneformer dependency that has removed something imported by gene former (more details here: https://github.com/chanzuckerberg/cellxgene-census/issues/1378#issuecomment-2756063864
* Stops clobbering import errors from geneformer, which should make it easier to debug future issues

Try managed runners

---

.github/workflows/full-unittests.yml
.github/workflows/py-dependency-check.yml
.github/workflows/py-unittests.yml
api/python/cellxgene_census/pyproject.toml
api/python/cellxgene_census/scripts/requirements-dev.txt
api/python/cellxgene_census/src/cellxgene_census/experimental/ml/huggingface/cell_dataset_builder.py
api/python/cellxgene_census/src/cellxgene_census/experimental/ml/huggingface/geneformer_tokenizer.py
api/python/cellxgene_census/tests/conftest.py
api/python/cellxgene_census/tests/experimental/ml/huggingface/test_geneformer.py

Mark Geneformer tests to disable them by default, and avoid installing Geneformer in CI due to dependency issues (#1378).

take Geneformer out of CI

---

tools/models/geneformer/Dockerfile
tools/models/geneformer/README.md
tools/models/geneformer/helpers/__init__.py
tools/models/geneformer/helpers/cell_dataset_builder.py
tools/models/geneformer/helpers/geneformer_tokenizer.py
tools/models/geneformer/prepare-census-geneformer-dataset.py
tools/models/geneformer/test_GeneformerTokenizer.py

Copying GeneformerTokenizer (and CellDatasetBuilder) to `tools/models/geneformer`, where it will live after eventual removal from the `cellxgene_census.experimental` API. Updates the Dockerfile there to run the GeneformerTokenizer unit tests to exercise the local installation.

copy GeneformerTokenizer into tools/models/geneformer
